### ISSUE TITLE
[Bug]: Incompatible licenses

### ISSUE THREAD

**Issue by CyberTailor** [LemmyNet/activitypub-federation-rust#57]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

`http-signature-normalization-0.6.0.crate` is licensed under CSL, which is incompatible with GPL licenses.

See:
https://lynnesbian.space/csl/

This issue prevents packaging Lemmy.

### Steps to Reproduce

None

### Technical Details

None

### Version

0.18.0

**Comment by Nutomic** [comment]
I moved the issue because this library is not required directly by Lemmy anymore. Its still used by the activitypub-federation library which Lemmy uses. However according to the [git repo](https://git.asonix.dog/asonix/http-signature-normalization#), at least the latest version is licensed under AGPL.

**Comment by pijuszczyk** [comment]
From the Cargo.toml, activitypub-federation library depends on http-signature-normalization-reqwest 0.8.0 and http-signature-normalization 0.7.0, which are both at the latest available version, licensed under AGPL. So there's nothing to be done except for removing the dependency from `lemmy` repo.
